class MyException extends Exception {
    private String teks;
    
    MyException(String s) {
        teks = "Exception generated by: " + s;
    }
    
    @Override
    public String toString() {
        return teks;
    }
}

class Eksepsi {
    static void tampil(String s) throws MyException {
        System.out.println("Tampil");
        if (s.equals("amir")) {
            throw new MyException(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) {
        try {
            tampil("ali");
            tampil("amir"); // Ini akan memicu exception
        } catch (MyException ex) {
            System.out.println("Tangkap: " + ex);
        }
    }
}